{{- if .Values.ingress.sslRedirect }}
{{- $fullName := include "releases-maxa-ai.fullname" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  labels:
    {{- include "releases-maxa-ai.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: {{ $fullName }}
  name: {{ $fullName }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "MOVED_PERMANENTLY_DEFAULT"
{{- end }}
